#index:
#    path: /
#    controller: App\Controller\DefaultController::index
search:
  path: /search
  methods: [GET]
  controller: App\Controller\AccountsController::search

app_accounts_delete:
  path: /users/delete/{id}
  controller: App\Controller\AccountsController::delete
  methods: [POST]

app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [POST, GET]


app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
  methods: [POST, GET]


admin_form_view:
  path: /admin/form/view/{id}
  controller: App\Controller\admin\CmsFormsController::show
  methods: [GET]

admin_template_form_edit:
  path: /admin/template/{templatePath}/edit/{id}
  controller: App\Controller\admin\TemplateFormController::edit
  methods: [POST, GET]

api_routes:
  path: /api/routes
  controller: App\Controller\admin\CmsFormsController::getRoutes
