#index:
#    path: /
#    controller: App\Controller\DefaultController::index
search:
  path: /search
  methods: [GET]
  controller: App\Controller\AccountsController::search

app_accounts_delete:
  path: /accounts/delete/{id}
  controller: App\Controller\AccountsController::delete
  methods: [POST]

app_login:
  path: /auth
  controller: App\Controller\AuthController::login
